package com.pe.biblioteca.components;

import com.pe.biblioteca.dao.LibroDao;
import com.pe.biblioteca.daoimpl.LibroDaoImpl;
import com.pe.biblioteca.modelo.Libro;
import com.pe.biblioteca.utils.Evento;
import com.pe.biblioteca.vista.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan
 */
public class LibrosForm extends javax.swing.JPanel {

    private LibroDao libroDao = new LibroDaoImpl();
    private boolean esEditar = false;
    private Libro libroEditar;
    private Evento evento = new Evento();

    public LibrosForm() {
        initComponents();
        txtIdLibro.setVisible(false);

    }

    public LibrosForm(Libro libro) {
        initComponents();
        esEditar = true;
        libroEditar = libro;
        txtIdLibro.setVisible(false);
        InitStyles();
    }

    public void InitStyles() {

        if (esEditar) {
            titulo.setText("Editar Libro");
            txtIdLibro.setEnabled(false);

            if (libroEditar != null) {
                txtIdLibro.setText(String.valueOf(libroEditar.getId()));
                txtTituloLibro.setText(libroEditar.getTitulo());
                txtAutorLibro.setText(libroEditar.getAutor());
                txtCategoriaLibro.setText(libroEditar.getCategoria());
                txtAnhoLibro.setText(String.valueOf(libroEditar.getAnhoPublicacion()));
                txtStockLibro.setText(String.valueOf(libroEditar.getStock()));

            }

        }
    }

    public void limpiarForm() {
        txtIdLibro.setText("");
        txtTituloLibro.setText("");
        txtAutorLibro.setText("");
        txtCategoriaLibro.setText("");
        txtAnhoLibro.setText("");
        txtStockLibro.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnRegistrarLIbro = new javax.swing.JButton();
        btnRegresarPanelLibro = new javax.swing.JButton();
        txtTituloLibro = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        txtIdLibro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAutorLibro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCategoriaLibro = new javax.swing.JTextField();
        titleLbl1 = new javax.swing.JLabel();
        txtStockLibro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAnhoLibro = new javax.swing.JTextField();

        bg.setBackground(new java.awt.Color(249, 245, 235));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titulo.setForeground(new java.awt.Color(96, 126, 170));
        titulo.setText("Registrar nuevo libro");

        btnRegistrarLIbro.setBackground(new java.awt.Color(28, 56, 121));
        btnRegistrarLIbro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarLIbro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarLIbro.setText("Guardar");
        btnRegistrarLIbro.setBorderPainted(false);
        btnRegistrarLIbro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarLIbro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLIbroActionPerformed(evt);
            }
        });

        btnRegresarPanelLibro.setBackground(new java.awt.Color(28, 56, 121));
        btnRegresarPanelLibro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresarPanelLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarPanelLibro.setText("Regresar");
        btnRegresarPanelLibro.setBorderPainted(false);
        btnRegresarPanelLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarPanelLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPanelLibroActionPerformed(evt);
            }
        });

        titleLbl.setForeground(new java.awt.Color(96, 126, 170));
        titleLbl.setText("Título:");

        jLabel2.setForeground(new java.awt.Color(96, 126, 170));
        jLabel2.setText("Autor:");

        jLabel3.setForeground(new java.awt.Color(96, 126, 170));
        jLabel3.setText("Categoria:");

        titleLbl1.setForeground(new java.awt.Color(96, 126, 170));
        titleLbl1.setText("Año de publicación: ");

        txtStockLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockLibroKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(96, 126, 170));
        jLabel1.setText("Stock:");

        txtAnhoLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnhoLibroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoriaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAnhoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(titleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStockLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(btnRegresarPanelLibro)
                                .addGap(14, 14, 14)
                                .addComponent(btnRegistrarLIbro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(258, 258, 258)))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titulo)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(titleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnhoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStockLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCategoriaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresarPanelLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarLIbro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarLIbroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLIbroActionPerformed
        // TODO add your handling code here:
        // Validaciones para los campos
        if ("".equals(txtTituloLibro.getText()) || "".equals(txtAutorLibro.getText()) || "".equals(txtCategoriaLibro.getText()) || "".equals(txtAnhoLibro.getText()) || "".equals(txtStockLibro.getText())) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", JOptionPane.ERROR_MESSAGE);
            txtTituloLibro.requestFocus();
            return;
        }
        String titulo = txtTituloLibro.getText();
        String autor = txtAutorLibro.getText();
        String categoria = txtCategoriaLibro.getText();
        int anhoPublicacion = Integer.parseInt(txtAnhoLibro.getText());
        int stock = Integer.parseInt(txtStockLibro.getText());

        Libro libro = esEditar ? libroEditar : new Libro();

        libro.setTitulo(titulo);
        libro.setAutor(autor);
        libro.setCategoria(categoria);
        libro.setAnhoPublicacion(anhoPublicacion);
        libro.setStock(stock);
        try {

            if (!esEditar) {
                libroDao.save(libro);
            } else {
                int id = Integer.parseInt(txtIdLibro.getText());
                libro.setId(id);
                libroDao.update(libro);
            }

            String successMsg = esEditar ? "modificado" : "registrado";

            JOptionPane.showMessageDialog(this, "Libro " + successMsg + " exitosamente.\n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            if (!esEditar) {
                limpiarForm();
            }
        } catch (Exception e) {
            String errorMsg = esEditar ? "modificar" : "registrar";
            JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el libro. \n", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarLIbroActionPerformed

    private void btnRegresarPanelLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPanelLibroActionPerformed
        // TODO add your handling code here:
        Sistema.ShowJPanel(new Libros());
    }//GEN-LAST:event_btnRegresarPanelLibroActionPerformed

    private void txtAnhoLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnhoLibroKeyTyped
        // TODO add your handling code here:
        evento.numberKeyPress(evt);
    }//GEN-LAST:event_txtAnhoLibroKeyTyped

    private void txtStockLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockLibroKeyTyped
        // TODO add your handling code here:
        evento.numberKeyPress(evt);
    }//GEN-LAST:event_txtStockLibroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrarLIbro;
    private javax.swing.JButton btnRegresarPanelLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel titleLbl1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtAnhoLibro;
    private javax.swing.JTextField txtAutorLibro;
    private javax.swing.JTextField txtCategoriaLibro;
    private javax.swing.JTextField txtIdLibro;
    private javax.swing.JTextField txtStockLibro;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
