package com.pe.biblioteca.components;

import com.formdev.flatlaf.json.ParseException;
import com.pe.biblioteca.dao.PrestamoDao;
import com.pe.biblioteca.daoimpl.PrestamoDaoImpl;
import com.pe.biblioteca.utils.ReporteExcel;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brayan
 */
public class Registros extends javax.swing.JPanel {

    PrestamoDao prestamoDao = new PrestamoDaoImpl();

    public Registros() {
        initComponents();
        InitStyles();
        try {
            cargarReportes();
        } catch (java.text.ParseException ex) {
            System.out.println(ex.toString());
        }
    }

    public void InitStyles() {
        tablaReportes.setRowSelectionAllowed(true);
    }

    private void cargarReportes() throws java.text.ParseException {
        List<HashMap<String, Object>> lista = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tablaReportes.getModel();
        lista = prestamoDao.findAll();
        Object[] datos = new Object[4];
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        SimpleDateFormat formatoSalida = new SimpleDateFormat("dd/MM/yyyy h:mm a");

        for (Map<String, Object> map : lista) {
            datos[0] = map.get("id");
            datos[1] = map.get("cliente");
            // Formatear la fecha de préstamo
            try {
                Date fechaPrestamo = formatoEntrada.parse(map.get("fecha_prestamo").toString());
                datos[2] = formatoSalida.format(fechaPrestamo);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            // Formatear la fecha de devolución
            if (map.get("fecha_entrega") != null) {
                try {
                    Date fechaDevolucion = formatoEntrada.parse(map.get("fecha_entrega").toString());
                    datos[3] = formatoSalida.format(fechaDevolucion);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            } else {
                datos[3] = "Pendiente";
            }
            //datos[2] = map.get("fecha_prestamo");
            //datos[3] = map.get("fecha_devolucion");
            model.addRow(datos);
        }
        tablaReportes.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1100, 650));

        bg.setBackground(new java.awt.Color(249, 245, 235));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titulo.setText("Reporte de préstamos");

        btnExcel.setBackground(new java.awt.Color(16, 28, 83));
        btnExcel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcel.setForeground(new java.awt.Color(255, 255, 255));
        btnExcel.setText("Excel");
        btnExcel.setBorderPainted(false);
        btnExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Fecha de Préstamo", "Fecha de devolución"
            }
        ));
        tablaReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaReportes.setFocusable(false);
        jScrollPane1.setViewportView(tablaReportes);
        if (tablaReportes.getColumnModel().getColumnCount() > 0) {
            tablaReportes.getColumnModel().getColumn(0).setMinWidth(35);
            tablaReportes.getColumnModel().getColumn(0).setPreferredWidth(35);
            tablaReportes.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaReportes.getModel();
        ReporteExcel.generateReport(modeloTabla);
    }//GEN-LAST:event_btnExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnExcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportes;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
